import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >

     <header className="px-8 py-2 flex justify-between items-center">
        <img
        className="rounded-full w-18" src="/images.png" alt="" />

        <div className="space-x-4">
          <Link className="p-3 bg-yellow-500 font-semibold hover:bg-amber-500 hover:text-white rounded-lg" href="/foods">Food</Link>
          <Link className="p-3 bg-yellow-500 rounded-lg font-semibold hover:bg-amber-500 hover:text-white" href="/reviews">Reviews</Link>
        </div>
      </header>
      

        <main className="px-8 py-4">
          {children}
        </main>
      </body>
    </html>
  );
}
