import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >

     <header className="px-5 py-3.5 flex justify-between ">
        <img
        className="rounded-full w-24 h-24" src="/images.png" alt="" />
      </header>
      

        {children}
      </body>
    </html>
  );
}
